### ISSUE TITLE
registry-experimental: let's have `compute summary` also compute a histogram of providers

### ISSUE THREAD

**Issue by timburks** [apigee/registry-experimental#198]
Currently it computes a histogram of MIME types:
```
shell:/# registry get artifacts/summary -o yaml
apiVersion: apigeeregistry/v1
kind: Summary
metadata:
  name: summary
data:
  apis: 724
  versions: 1234
  specs: 1452
  mimetypes:
    application/x.awsconfig+zip: 360
    application/x.discovery+gzip: 410
    application/x.graphql+gzip: 1
    application/x.openapi+gzip;version=2.0: 324
    application/x.openapi+gzip;version=3: 15
    application/x.openapi+gzip;version=3.0.0: 2
    application/x.openapi+gzip;version=3.0.1: 42
    application/x.openapi+gzip;version=3.0.3: 2
    application/x.protobuf+zip: 296
```

Let's do the same for the `provider` label, shown below in a sample API:
```
shell:/# registry get apis/google.com-apigeeregistry -o yaml
apiVersion: apigeeregistry/v1
kind: API
metadata:
  name: google.com-apigeeregistry
  labels:
    provider: google-com
    source: import-google-protos
    updated: "2023-05-18"
data:
  displayName: Google Apigee Registry API
```
